### ISSUE TITLE
Thundra causes exception in lambda that uses SSM

### ISSUE THREAD

**Issue by nshgraph** [thundra-io/thundra-lambda-agent-python#60]
SSM is important for secrets management.
Thundra injects itself into botocore and tries to wrap functions. But if it doesn't have a subclass for the required function it just crashes.
```
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/thundra/integrations/modules/botocore.py", line 22, in _wrapper
response = INTEGRATIONS[integration_name].create_span(
KeyError: 'ssm'
```
The issue didn't exist before adding thundra, and removing thundra makes the issue go away.

Note: this happens in a call to boto3 that occurs before thundra agent is loaded:
```
        ssm_client = boto3.client('ssm', region_name='us-east-1')
        response = ssm_client.get_parameter(parameter_name)
```

**Comment by hamitb** [comment]
Hi @nshgraph,

That was a problem that we know about and it's been a while since we have fixed it. Could you please make sure that you are using the latest version of the agent (which is 2.2.3 by the time I wrote this). I have also tried to reproduce your issue using the latest version of the agent and but I couldn't. So there shouldn't be a problem once you update your agent.

Also, it would be good if you can let us know after trying with the new version of the agent, whether the problem is solved.
